-- No-op: original body created leases / lease_signatures / lease_audit_logs.
-- (a) That schema already exists remotely (this repo's migration history only tracks
--     20260707144339+ remotely; this file is a local-only record of pre-existing schema).
-- (b) The `leases` table is documented dead (see CONTEXT.md "Lease Agreement" glossary
--     entry: canonical record is lease_contracts, not the dead `leases` table).
-- (c) The original body referenced properties before public.properties existed
--     (properties is created in 20250804103254_*.sql), which broke fresh local
--     `supabase db reset` replay.
-- Body removed so reset applies cleanly. A no-op migration is valid.
