-- No-op: original body created a TEXT-role variant of public.user_roles plus
-- has_role(UUID, TEXT) / current_user_has_role(TEXT).
-- (a) The canonical user_roles (role user_role enum) and has_role(UUID, user_role)
--     are created in 20250804103254_*.sql, which everything downstream depends on;
--     remote already has that schema (remote migration history only tracks
--     20260707144339+; this file is a local-only record).
-- (b) On fresh local replay this file's CREATE TABLE IF NOT EXISTS won the race,
--     making 20250804103254's plain CREATE TABLE public.user_roles fail
--     (relation already exists) and breaking `supabase db reset`.
-- (c) current_user_has_role is referenced nowhere in migrations or app code, and the
--     TEXT has_role overload would make untyped calls like has_role(auth.uid(), 'admin')
--     ambiguous against the canonical enum overload.
-- Body removed so reset applies cleanly. A no-op migration is valid.
