-- No-op: original body was the first draft of the viewing_slots/viewing_reminders
-- creation, superseded 52 seconds later by 20250908173443_*.sql, which is identical
-- except viewing_slots.thread_id is renamed to conversation_id (the name app code uses).
-- Replaying both broke fresh local `supabase db reset`: the second file's
-- `create type viewing_status`, policies, trigger and publication statements all
-- collided with this one's, and its conversation_id index failed because this file's
-- thread_id table shape won the create-if-not-exists race.
-- Remote is unaffected: remote migration history only tracks 20260707144339+.
-- Body removed so the later file is the single source of these objects.
