-- No-op: superseded by 20250916204857, its guarded retry (IF NOT EXISTS +
-- pg_policies checks), created 97s later. This file's plain CREATE TABLE
-- public.lease_templates collided with 20250805072647's (whose
-- template_content shape matches the generated remote types), breaking fresh
-- local `supabase db reset` replay. The only statements 204857 does not
-- repeat are the two updated_at triggers, which also never applied remotely
-- (execution aborted at the lease_templates collision); add via a new
-- migration if lease_contracts.updated_at maintenance is ever needed.
