-- No-op: original body used `CREATE POLICY IF NOT EXISTS` (invalid Postgres
-- syntax), so it can never have executed anywhere; 20250812192157 is the
-- corrected retry creating the same landlord screening-details policy.
-- (Dash-named `<version>-.sql` files were skipped by the CLI's migration glob
-- until renamed to _legacy.sql on 2026-07-10, which is when this surfaced.)
