-- No-op: original body used `CREATE POLICY IF NOT EXISTS`, which is not valid
-- Postgres syntax — this file can never have applied anywhere (it always errors).
-- Its corrected, idempotent twin is 20250810163951_*.sql (same table, constraint,
-- indexes and policies, wrapped in duplicate_object guards), which applies right after.
-- Body removed so fresh local `supabase db reset` applies cleanly.
