-- No-op: original body created public.inventory_records / inventory_items / inventory_reports.
-- (a) That schema already exists remotely (this repo's migration history only tracks
--     20260707144339+ remotely; this file is a local-only record of pre-existing schema).
-- (b) The inventory feature is retired on this branch (dropped by a later migration;
--     see CONTEXT.md "Condition Record" glossary entry noting Inventory is retired).
-- (c) The original body referenced public.properties before that table existed
--     (properties is created in 20250804103254_*.sql), which broke fresh local
--     `supabase db reset` replay.
-- Body removed so reset applies cleanly. A no-op migration is valid.
